---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/cznewt/goarchitect.git
    branch: concourse

- name: daily-build
  type: time
  source:
    interval: 24h

jobs:
- name: test
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - get: daily-build
    trigger: true

  - aggregate:
    - task: test-latest
      file: code/concourse/task-golang-latest.yml
    - task: test-1.9
      file: code/concourse/task-golang-1.8.yml
    - task: test-1.8
      file: code/concourse/task-golang-1.9.yml
